---
- name: "Authenticate with master credentials to the master realm"
  run_once: true
  uri:  
    method: POST
    url: "http://localhost:8080/auth/realms/master/protocol/openid-connect/token"
    body: "username={{ keycloak_admin_user }}&password={{ keycloak_admin_password }}&grant_type=password&client_id=admin-cli"
    return_content: true
  register: authenticate_response

- name: "Get the realm matching the instance name if it exists"
  run_once: true
  uri:
    method: GET
    url: "http://localhost:8080/auth/admin/realms/{{ safe_instance_name }}"
    headers:
      'Authorization': "{{ authenticate_response.json.token_type }} {{ authenticate_response.json.access_token }}"
    return_content: true
  register: realm_response
  failed_when: not (realm_response.status == 200 or realm_response.status == 404)

- name: "If the realm is not found then create it"
  run_once: true
  uri:
    method: POST
    url: "http://localhost:8080/auth/admin/realms"
    headers:
      'Authorization': "{{ authenticate_response.json.token_type }} {{ authenticate_response.json.access_token }}"
    body: "{'id': '{{ safe_instance_name }}', 'realm': '{{ safe_instance_name }}', 'displayName': 'OCP Realm', 'enabled': true}"
    body_format: json
    return_content: true
  changed_when: realm_creation.status == 201
  failed_when: not (realm_creation.status == 200 or realm_creation.status == 201)
  register: realm_creation
  when: "realm_response.status == 404" # when realm is not found

- name: "In that realm look for the client template that will be used for the client"
  run_once: true
  uri:
    method: GET
    url: "http://localhost:8080/auth/admin/realms/{{ safe_instance_name }}/client-templates/client_template_{{ safe_instance_name }}"
    headers:
      'Authorization': "{{ authenticate_response.json.token_type }} {{ authenticate_response.json.access_token }}"
    return_content: true
  register: client_template_response
  failed_when: not (client_template_response.status == 200 or client_template_response.status == 404)

- name: "If the client template is not found then get create it"
  run_once: true
  uri:
    method: POST
    url: "http://localhost:8080/auth/admin/realms/{{ safe_instance_name }}/client-templates"
    headers:
      'Authorization': "{{ authenticate_response.json.token_type }} {{ authenticate_response.json.access_token }}"
    body: "{'id': 'client_template_{{ safe_instance_name }}', 'name': 'client_template_{{ safe_instance_name }}'}"
    body_format: json
    return_content: true
  register: client_template_creation
  changed_when: client_template_creation.status == 201
  failed_when: not (client_template_creation.status == 200 or client_template_creation.status == 201)
  when: "client_template_response.status == 404" # when client template is not found

- name: "Get the list of clients filtering with the client id so that there will be no response list if the client is not found"
  run_once: true
  uri:
    method: GET
    url: "http://localhost:8080/auth/admin/realms/{{ safe_instance_name }}/clients?clientId=client_{{ safe_instance_name }}"
    headers:
      'Authorization': "{{ authenticate_response.json.token_type }} {{ authenticate_response.json.access_token }}"
    return_content: true
  register: client_list_response

- name: "Use the found client id to get the client details (if a client is found)"
  run_once: true
  uri:
    method: GET
    url: "http://localhost:8080/auth/admin/realms/{{ safe_instance_name }}/clients/{{ client_list_response.json[0].id }}"
    headers:
      'Authorization': "{{ authenticate_response.json.token_type }} {{ authenticate_response.json.access_token }}"
    return_content: true
  register: client_response
  when: (client_list_response.json is defined) and (client_list_response.json | length > 0)

- name: "Use variable from client response if client responded"
  set_fact:
    keycloak_details: "{{ client_response.json }}"
  when: (client_list_response.json is defined) and (client_list_response.json | length > 0)

- name: "If no client was found then create the client"
  run_once: true
  uri:
    method: POST
    url: "http://localhost:8080/auth/admin/realms/{{ safe_instance_name }}/clients"
    headers:
      'Authorization': "{{ authenticate_response.json.token_type }} {{ authenticate_response.json.access_token }}"
    body: "{'clientId': 'client_{{ safe_instance_name }}', 'name': 'client_{{ safe_instance_name }}', 'clientTemplate': 'client_template_{{ safe_instance_name }}', 'enabled': true}"
    body_format: json
    return_content: true
  register: client_creation
  changed_when: client_creation.status == 201
  failed_when: not (client_creation.status == 200 or client_creation.status == 201)
  when: not ((client_list_response.json is defined) and (client_list_response.json | length > 0))

- debug:
    var: client_creation
  when: client_creation.changed

- name: "Use client creation response for future data"
  run_once: true
  set_fact: 
    keycloak_details: "{{ client_creation.json }}"
  when: client_creation.changed

- name: "Get client secret for later so that it can be used for authentication"
  run_once: true
  uri:
    method: GET
    url: "http://localhost:8080/auth/admin/realms/{{ safe_instance_name }}/clients/{{ keycloak_details.id }}/client-secret"
    headers:
      'Authorization': "{{ authenticate_response.json.token_type }} {{ authenticate_response.json.access_token }}"
    return_content: true
  register: client_secret_response # {type='secret', .value='...'}

- name: "Set client secret for later use"
  run_once: true
  set_fact:
    keycloak_client_secret: "{{ client_secret_response.json.value }}"

- name: "Consolidate facts for storage"
  run_once: true
  set_fact:
    keycloak_details: "{{ keycloak_details | combine({'secret': keycloak_client_secret}) }}"

# write facts to external file to preserve for later
- name: "Write keycloak facts to preserve for later"
  run_once: true
  copy: 
    dest: "/tmp/keycloak_details.yml"
    content: "---\n{{ keycloak_details | to_nice_yaml }}"

- name: "Fetch keycloak details into a file on localhost"
  run_once: true
  fetch:
    src: "/tmp/keycloak_details.yml"
    dest: "{{ playbook_dir }}/static/{{ safe_instance_name }}/keycloak_details.yml"
    flat: true
    fail_on_missing: true
