---
- name: "Install required prerequisites"
  package:
    name: 
      - "epel-release"

- name: "Load keycloak_details if a previous run has made them available"
  include_vars:
    file: "./static/{{ safe_instance_name }}/keycloak_details.yml"
    name: "keycloak_details"

# include each piece
- include: "nginx.yml"
  when: not keycloak_details is defined and not force_keycloak

- include: "keycloak.yml"
  when: not keycloak_details is defined and not force_keycloak