---
# nginx install
- name: "Install nginx and deps"
  package:
    name: 
      - "nginx"

# allow (another) non-standard http port
- name: "Allow non-standard port 8000 to host an HTTP service"
  seport:
    ports: 8000
    proto: tcp
    setype: http_port_t
    state: present

- name: "Allow HTTPD to make network connections"
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

# make sure nginx service is enabled
- name: "Enable nginx service"
  service:
    name: "nginx"
    enabled: true
    daemon_reload: true

# set up nginx to just redirect and proxy as needed
- name: "Copy nginx configuration template"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 644
  notify: 
    - restart nginx
