---
# playbook to create OCP on demand in a VPC in EC2 with 
# a configurable number of nodes.

# info
# see more here: https://docs.openshift.com/container-platform/3.4/install_config/install/advanced_install.html#running-the-advanced-installation
# 

# ensure that localhost has the static folder structure for info that spans multiple runs
- hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - "always"
  tasks:
    - name: "Ensure static structure is present"
      file:
        path: "./static/{{ safe_instance_name }}"
        state: directory

# create ec2 infrastructure (from localhost, making only needed changes to get the ec2 client running)
- hosts: localhost
  connection: local
  gather_facts: false
  tags: 
    - "all"
    - "spinup"
  roles: 
    - "ec2_spinup"

# load variables if not loaded
- hosts: all
  gather_facts: false
  tags:
    - "always"
  tasks:
    - name: "Load variables if not defined"
      include_vars: 
        file: "./static/{{ safe_instance_name }}/ec2_info.yml"
        name: "ec2_info"
      when: not ec2_info is defined

# configure bastion host to recieve and execute commands
- hosts: bastion
  tags:
    - "all"
    - "bastion"
  roles: 
    - "common"
    - "bastion"

# configure keycloak system
- hosts: keycloak
  tags:
    - "all"
    - "post-spinup"
    - "keycloak"
  roles:
    - "common"
    - "keycloak"

# read keycloak facts and then add host variables as required
- hosts: localhost
  connection: local
  tags:
    - "all"
    - "ocp"
    - "keycloak"
    - "keycloak_details"
  roles:
    - "keycloak_details"

# subscribe rhel hosts 1 at a time
- hosts: rhel
  gather_facts: false # don't need facts, just do simple subscribe before continuing
  tags: 
    - "all"
    - "post-spinup"
    - "rhel"
    - "subscribe"
    - "common"
  roles:
    - "rhn_subscribe" # need to attach to rhn before attending to common tasks
  serial: 2 # limit so that RHN doesn't freak out and throw SQL exceptions

# configure rhel hosts
- hosts: rhel
  tags:
    - "all"
    - "post-spinup"
    - "rhel"
  roles:
    - "rhel" # any rhel-specific host stuff
    - "common" # common packages after rhel repos have been handled

# configure nodes
- hosts: nodes
  tags: 
    - "all"
    - "post-spinup"
    - "nodes"
  roles:
    - "node-pre"

# check out and prepare to execute byo playbook
- hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - "all"
    - "post-spinup"
    - "prep"
  roles:
    - "prepare"

# from recent checkout execute the byo configuration script
- include: "{{ playbook_dir }}/static/openshift-ansible/playbooks/byo/config.yml"
  tags:
    - "all"
    - "post-spinup"
    - "ocp"

# finalize nodes
- hosts: nodes
  tags:
    - "all"
    - "finalize"
  roles:
    - "finalize"
