---
# test wildfly
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Postgres Driver"
      wildfly_api: 
        username: "keycloak"
        password: "keycloak"
        operation: present
        address:
          - {"subsystem": "datasources"}
          - {"jdbc-driver": "postgresql"}
        parameters:
          driver-name: "postgresql"
          driver-module-name: "org.postgresql"          
          driver-xa-datasource-class-name: "org.postgresql.xa.PGXADataSource"

    - name: "Postgres-based datasource"
      wildfly_api:
        username: "keycloak"
        password: "keycloak"
        operation: present
        address:
          - {"subsystem": "datasources"}
          - {"data-source": "KeycloakDS"}
        parameters:
          driver-name: "h2"
          jndi-name: "java:jboss/datasources/KeycloakDS"
          user-name: "sa"
          password: "sa"
          connection-url: "jdbc:h2:${jboss.server.data.dir}/keycloak-test-url-change;AUTO_SERVER=TRUE"
          enabled: true
          use-java-context: true





    

