---
- name: "Ensure s3 bucket is deleted"
  s3:
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    bucket: "{{ bucket_prefix }}-registry"
    mode: delete