---
- name: "Enable base set of repositories"
  command: "subscription-manager repos --disable=rhel* --enable=rhel-7-server-rpms --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-eus-rpms --enable=rhel-7-server-eus-optional-rpms --enable=rhel-7-server-aus-rpms --enable=rhel-7-server-aus-optional-rpms"
  register: repos_enabled

- name: "Enable OSE/OCP required repositories"
  command: "subscription-manager repos --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-ose-{{ ocp_version }}-rpms"
  register: ocp_repos_enabled

- name: "Ensure required packages are installed"
  yum:
    state: present
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "atomic-openshift-utils"
      - "atomic-openshift-excluder"
      - "atomic-openshift-docker-excluder"
      - "docker"

- name: "Update all packages"
  yum:
    name: "*"
    state: latest

- name: "Set up Docker to use an insecure registry"
  lineinfile:
    path: "/etc/sysconfig/docker"
    regexp: "^OPTIONS"
    line: "OPTIONS='--selinux-enabled --insecure-registry 172.30.0.0/16'"

- name: "Copy docker storage setup configuration"
  template:
    src: "docker-storage-setup.j2"
    dest: "/etc/sysconfig/docker-storage-setup"
  register: storage_template

- name: "Set up Docker storage"
  command: "docker-storage-setup"
  when: ansible_lvm is defined and ((not 'docker-vg' in ansible_lvm.vgs) or storage_template.changed)

- name: "Docker should be started once everything is configured"
  service:
    name: "docker"
    state: started

