---
# wait for (!!!) minutes
- name: "Wait for RDS because the wait=true on the create RDS takes longer than the timeout window"
  pause:
    minutes: 1
  when: keycloak_db_create_result.changed or keycloak_db_create_result.instance.endpoint is not defined

# create RDS for keycloak, this might seem a little weird but this is because we've waited 
# longer than the timeout window to give this thing time to start up
- name: "Ensure RDS is created"
  rds:
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"    
    command: create
    instance_name: "{{ safe_instance_name }}-keycloak-db"
    db_engine: postgres
    port: 5432
    size: 5
    instance_type: "{{ keycloak_rds_size }}"
    username: "keycloak"
    password: "{{ keycloak_db_password }}"
    subnet: "{{ safe_instance_name }}-db-subnet-group"
    vpc_security_groups:
      - "{{ postgres_security_group_result.group_id }}"
    tags:
      instance: "{{ instance_name }}"
      Name: "{{ instance_name }}-keycloak-db"
    maint_window: "Mon:23:00-Tue:03:15"
    wait: true
  register: keycloak_db_result