---
- name: "Ensure s3 bucket is created"
  s3:
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    bucket: "{{ bucket_name }}"
    mode: create
    permission: private
  register: s3_bucket

- name: "Create VPC endpoint for created bucket"
  extras_ec2_vpc_endpoint:
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_result.vpc.id }}"
    service: "com.amazonaws.{{ aws_region }}.s3"
    route_table_ids:
      - "{{ private_route_table.route_table.id }}"
  register: s3_vpc_endpoint