---
# make sure boto and boto3 are installed for aws/ec2 tools
- name: "Install AWS client dependencies"
  pip:
    name: 
      - "boto"
      - "boto3"
      - "pyOpenSSL"

# ensure that the cloud host name is managed by route53
- route53_zone:
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    zone: "{{ hosted_zone }}"
    state: present
  when: manage_host

# pre-vpc stuff (like keypair)
- include: "00_setup.yml"

# vpc and networking bits
- include: "01_vpc.yml"

# spin up nodes
- include: "02_nodes.yml"

# create and manage database instance
- include: "03_rds.yml"

# set up application load balancing
- include: "04_alb.yml"

# we need to keep some facts from this run
# you can get here via: `hostvars['localhost']['ec2_info']` from elsewhere
- name: "Maintain facts to use later in the run by other modules"
  set_fact:
    ec2_info:
      masters: " {{ master_instances }}"
      infras: "{{ infra_instances }}"
      nodes: "{{ node_instances }}"
      keycloak: "{{ keycloak_instances }}"
      keycloak_db: "{{ keycloak_db_result }}"
      subnets: "{{ subnets }}"

# set up dynamic variables/inventory
- name: "Copy generated/dynamic host template"
  template:
    dest: "./hosts/dynamic"
    src: "dynamic_hosts.j2"
