---
# make sure boto and boto3 are installed for aws/ec2 tools
- name: "Install AWS client dependencies"
  pip:
    name: 
      - "boto"
      - "boto3"
      - "pyOpenSSL"

# check for previous ec2 info
- name: "Check if EC2 instance information exists"
  stat:
    path: "static/{{ safe_instance_name }}/ec2_info.yml"
  register: ec2_info_stat

# if there is no information you can spinup the instances or if force_spinup is true
- include: "spinup.yml"
  when: (not ec2_info_stat.stat.exists) or (force_spinup | bool)
  
# if spun up already and no ec2_info is loaded directly we can load it here
- name: "Load information from ec2_info.yml if it was not loaded during spinup phase"  
  include_vars: 
    file: "./static/{{ safe_instance_name }}/ec2_info.yml"
    name: "ec2_info"
  register: ec2_loaded
  when: not ec2_info is defined

# set up dynamic variables/inventory
- name: "Copy generated/dynamic host template"
  template:
    dest: "./hosts/dynamic"
    src: "dynamic_hosts.j2"
  register: new_hosts

# reload host information
- name: "Reload host information"
  meta: refresh_inventory
  when: ec2_loaded.changed or new_hosts.changed

# we can't continue without this information
- name: "Fail if no instance information is found"
  fail:
    msg: "No ec2_info present, spinup or reading values has failed"
  when: not ec2_info is defined