---
- name: "Latest RHSM / configuration packages if possible"
  yum:
    state: latest
    name:
      - "python-rhsm" 
      - "subscription-manager"

- name: "Quickly gather subscription details"
  shell: "subscription-manager status | grep Overall | awk '{print $3}'"
  register: subscription_status
  changed_when: false

- name: "Subscribe to Red Hat repositories in pool that has access to OSE/OCP artifacts"
  command: "subscription-manager register --insecure --force --username={{ rhn_username }} --password=\"{{ rhn_password }}\""
  when: "\"Current\" not in subscription_status.stdout"
  register: subscription_result

- name: "Get information on pool usage"
  command: "subscription-manager list --consumed --pool-only"
  register: pool_status
  changed_when: false

- name: "Attach to pool if required or if subscription was changed"
  command: "subscription-manager attach --pool={{ rhn_pool }}"
  when: pool_status.stdout_lines | length < 1 or subscription_result.changed
  register: attach_result
  failed_when: "attach_result.stderr is defined and attach_result.stderr != "" and (not \"Successfully\" in attach_result.stderr)"