---
- name: "Copy id_rsa to use inside protected networks"
  copy:
    src: "static/{{ instance_name }}.id_rsa"
    dest: "/root/.ssh/id_rsa"
    mode: 0400

- name: "Copy id_rsa to use inside protected networks"
  copy:
    src: "static/{{ instance_name }}.id_rsa"
    dest: "/home/{{ centos_user }}/.ssh/id_rsa"
    owner: "{{ centos_user }}"
    group: "{{ centos_user }}"
    mode: 0400

- name: "Wait for other (private network) hosts to come up so they can be managed"
  wait_for: 
    port: 22
    host: "{{ item }}"
  with_items: "{{ groups['tunneled'] }}"

  

