---
- name: "Install common utility packages"
  yum:
    name: 
      - "vim"
      - "nano"
      - "wget"
      - "curl"
      - "bind-utils"
      - "deltarpm"
      - "yum-utils"
    state: present